name: flutter_villains
description: Villains for flutter. Page transitions with just a few lines of code. What are heroes without villains?
version: 1.2.1
author: Norbert Kozsir <kozsir.norbert@gmail.com>
homepage: https://github.com/Norbert515/flutter_villains

environment:
  sdk: ">=2.2.0 <3.0.0"
dependencies:
  flutter_web: any
  flutter_web_ui: any